<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LMKUKFJ" failures="1" tests="14" name="Freedo_domain.dashboard" time="213.052" errors="0" timestamp="2023-03-06T16:48:32 IST" skipped="1">
  <testcase classname="Freedo_domain.dashboard" name="TC_001_verify_valid_launch_of_web_application" time="0.104"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_010_verify_valid_Booking_Statistics_count" time="1.965"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_011_verify_valid_Booking_list_as_per_booking_tabs" time="8.826"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_008_verify_valid_Vehicle_statistics_count" time="9.081"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_009_verify_valid_User_Statistics_count" time="1.875"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_006_verify_content_Home_page_of_Admin" time="51.782"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_003_verify_invalid_Login_functionality" time="9.529">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Freedo_domain.dashboard.TC_003_verify_invalid_Login_functionality(dashboard.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_003_verify_invalid_Login_functionality -->
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_012_verify_valid_Action_functionallity" time="51.145"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_014_verify_admin_approve_request" time="36.606"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_013_verify_valid_Action_View_icon_functionallity" time="1.087"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_005_verify_valid_Login_funcationality" time="11.013"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_002_verify_invalid_launch_of_web_application" time="20.354"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_007_verify_content_of_Dashboard" time="9.685"/>
  <system-out/>
  <testcase classname="Freedo_domain.dashboard" name="TC_004_verify_max_invalid_Login_attempt">
    <skipped/>
  </testcase> <!-- TC_004_verify_max_invalid_Login_attempt -->
  <system-out/>
</testsuite> <!-- Freedo_domain.dashboard -->
